version: '2'
services:
  api:
    build: ./issues-service
    volumes:
      - .:/app
    image: issues-backend_api:latest
    ports:
     - "8000:8000"
    restart: always
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./test-database
    ports:
      - "3307:3307"
    image: issues-backend_db:latest
